#
# Module manifest for module 'NAV installer'
#
# Generated by: Donny Chen
#
# Generated on: 2017-11-23
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'c9a7dbd8-c066-44c4-ab86-cef4168be5c1'

# Author of this module
Author = 'Donny Chen'

# Company or vendor of this module
CompanyName = 'Microsoft'

# Copyright statement for this module
Copyright = 'Copyright 2017 Microsoft'

# Description of the functionality provided by this module
Description = 'Install NAV'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'SQLPS'
)

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @(
    'Common\Expand-ZipFile',
    'Common\Import-NAVIdeModule',
    'Common\Import-NAVMgmtModule',
    'Common\Import-SqlPsModule',
    'Common\Invoke-ProcessWithProgress',
    'Log\Get-ExceptionString',
    'NAV\Copy-NAVSetup',
    'NAV\Import-FobOrTxtFile',
    'NAV\Import-NAVLicense',
    'NAV\Invoke-NAVCompile',
    'NAV\Invoke-NavSetup',
    'NAV\Start-NavServer',
    'NAV\Stop-NavServer',
    'SQL\Convert-NAVDatabase', 
    'SQL\Remove-SqlDatabase',
    'SQL\Restore-RTMDatabase',
    'SQL\Sync-NAVDatabase',
    'Log\Write-Exception',
    'Log\Write-Log',
    'NAV\UninstallNAVAll'
    )

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'Common\Expand-ZipFile.psm1',
    'Common\Import-NAVIdeModule.psm1',
    'Common\Import-NAVMgmtModule.psm1',
    'Common\Import-SqlPsModule.psm1',
    'Common\Invoke-ProcessWithProgress.psm1',
    'Log\Get-ExceptionString.psm1',
    'NAV\Copy-NAVSetup.psm1',
    'NAV\Import-FobOrTxtFile.psm1',
    'NAV\Import-NAVLicense.psm1',
    'NAV\Invoke-NAVCompile.psm1',
    'NAV\Invoke-NavSetup.psm1',
    'NAV\Start-NavServer.psm1',
    'NAV\Stop-NavServer.psm1',
    'SQL\Convert-NAVDatabase.psm1', 
    'SQL\Remove-SqlDatabase.psm1',
    'SQL\Restore-RTMDatabase.psm1',
    'SQL\Sync-NAVDatabase.psm1',
    'Log\Write-Exception.psm1',
    'Log\Write-Log.psm1',
    'NAV\UninstallNAVAll.psm1'
    )

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}


# SIG # Begin signature block
# MIIDzQYJKoZIhvcNAQcCoIIDvjCCA7oCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUy5IvIh1UAUs/d1zlNJFIn3du
# 1uegggH1MIIB8TCCAV6gAwIBAgIQerav1OJGjJREr2hDMeEqHzAJBgUrDgMCHQUA
# MA4xDDAKBgNVBAMTA05BVjAeFw0xNzExMjgwNDAwMzlaFw0zOTEyMzEyMzU5NTla
# MA4xDDAKBgNVBAMTA05BVjCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAp5GZ
# c6U30Wj/1Y5mmZpi4BU7Cy1Pbo7gDOVnxvIHCi1Bfivb7WQB3cpp1b2vYeBgH3y0
# Cl9th4bgTy9fPe/zdin57thq/OwJS3qB8rxKazh+Xa3BpHxvAumX7THqZ8ocvirB
# JGIl3K9fDUyeRkPDKq+CC0eqnKDaS6ANuHdvCg8CAwEAAaNYMFYwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwPwYDVR0BBDgwNoAQEgOra+cR2aH3BOGG7Qzr1qEQMA4xDDAK
# BgNVBAMTA05BVoIQerav1OJGjJREr2hDMeEqHzAJBgUrDgMCHQUAA4GBABelU7ZT
# +OXIZH2HfiD4Ngv7lef7RGEaLtBCiXyxkcmTInxY8s6FImkD0Hywf1jcDcU3LeEt
# QnxDsQvfkUFBRHhzFIUvhCxmTHgKfDvisV07bOIrraHuCUAQ+72yrQ7HSRQ5p9z4
# B98bWycdUXSY7mg5l6VilFT2A2Bs03U0WZ82MYIBQjCCAT4CAQEwIjAOMQwwCgYD
# VQQDEwNOQVYCEHq2r9TiRoyURK9oQzHhKh8wCQYFKw4DAhoFAKB4MBgGCisGAQQB
# gjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
# KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFGiS2f3J
# u7VYVClTrCydXc0tAQ6VMA0GCSqGSIb3DQEBAQUABIGAby2wcKM0VznhOydU6l0F
# HnoCwZ7E15BWtgjM86BCLl+I1dxgBDz14zAVvUsTyG2n5mdFkYXhihDHXAQwNDou
# RG8N7GptJSBmrEsgI3Qu/PctLqU6Qx+lrVqdlfynLoXYkRHiwAtNX0vo0OiUEADW
# 7eBrM2enhlwJr4n/OmIyVo4=
# SIG # End signature block
